// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _fir_filter_HH_
#define _fir_filter_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "fir_filter_dadd_6cud.h"
#include "fir_filter_dmul_6dEe.h"
#include "fir_filter_sitodpeOg.h"
#include "fir_filter_mask_tbkb.h"

namespace ap_rtl {

struct fir_filter : public sc_module {
    // Port declarations 10
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_out< sc_lv<5> > x_ant_address0;
    sc_out< sc_logic > x_ant_ce0;
    sc_in< sc_lv<16> > x_ant_q0;
    sc_out< sc_lv<5> > x_coefs_address0;
    sc_out< sc_logic > x_coefs_ce0;
    sc_in< sc_lv<32> > x_coefs_q0;
    sc_in< sc_lv<1> > dcValEn;
    sc_out< sc_lv<16> > ap_return;
    sc_signal< sc_logic > ap_var_for_const0;
    sc_signal< sc_lv<64> > ap_var_for_const1;


    // Module declarations
    fir_filter(sc_module_name name);
    SC_HAS_PROCESS(fir_filter);

    ~fir_filter();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    fir_filter_mask_tbkb* mask_table1_U;
    fir_filter_dadd_6cud<1,5,64,64,64>* fir_filter_dadd_6cud_U1;
    fir_filter_dmul_6dEe<1,6,64,64,64>* fir_filter_dmul_6dEe_U2;
    fir_filter_sitodpeOg<1,6,32,64>* fir_filter_sitodpeOg_U3;
    sc_signal< sc_lv<6> > mask_table1_address0;
    sc_signal< sc_logic > mask_table1_ce0;
    sc_signal< sc_lv<52> > mask_table1_q0;
    sc_signal< sc_lv<26> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<5> > i_fu_195_p2;
    sc_signal< sc_lv<5> > i_reg_626;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > icmp_ln18_fu_189_p2;
    sc_signal< sc_lv<32> > x_coefs_load_reg_641;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<16> > x_ant_load_reg_646;
    sc_signal< sc_lv<32> > mul_ln20_fu_210_p2;
    sc_signal< sc_lv<32> > mul_ln20_reg_651;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<32> > y_1_fu_215_p2;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<64> > grp_fu_185_p1;
    sc_signal< sc_lv<64> > tmp_reg_661;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_lv<64> > grp_fu_180_p2;
    sc_signal< sc_lv<64> > tmp_6_reg_666;
    sc_signal< sc_logic > ap_CS_fsm_state16;
    sc_signal< sc_lv<64> > select_ln24_fu_220_p3;
    sc_signal< sc_lv<64> > select_ln24_reg_671;
    sc_signal< sc_lv<64> > grp_fu_176_p2;
    sc_signal< sc_lv<64> > x_assign_reg_676;
    sc_signal< sc_logic > ap_CS_fsm_state21;
    sc_signal< sc_lv<1> > p_Result_s_reg_682;
    sc_signal< sc_logic > ap_CS_fsm_state22;
    sc_signal< sc_lv<11> > tmp_V_reg_691;
    sc_signal< sc_lv<52> > tmp_V_1_fu_248_p1;
    sc_signal< sc_lv<52> > tmp_V_1_reg_699;
    sc_signal< sc_lv<63> > trunc_ln368_fu_267_p1;
    sc_signal< sc_lv<63> > trunc_ln368_reg_710;
    sc_signal< sc_lv<1> > icmp_ln849_fu_271_p2;
    sc_signal< sc_lv<1> > icmp_ln849_reg_715;
    sc_signal< sc_logic > ap_CS_fsm_state23;
    sc_signal< sc_lv<1> > icmp_ln849_1_fu_276_p2;
    sc_signal< sc_lv<1> > icmp_ln849_1_reg_722;
    sc_signal< sc_lv<64> > p_Result_8_fu_349_p4;
    sc_signal< sc_lv<64> > p_Result_8_reg_728;
    sc_signal< sc_lv<1> > icmp_ln19_fu_359_p2;
    sc_signal< sc_lv<1> > icmp_ln19_reg_733;
    sc_signal< sc_lv<1> > icmp_ln19_1_fu_364_p2;
    sc_signal< sc_lv<1> > icmp_ln19_1_reg_738;
    sc_signal< sc_lv<1> > p_Result_9_reg_743;
    sc_signal< sc_logic > ap_CS_fsm_state24;
    sc_signal< sc_lv<11> > tmp_V_4_reg_748;
    sc_signal< sc_lv<52> > tmp_V_5_fu_452_p1;
    sc_signal< sc_lv<52> > tmp_V_5_reg_754;
    sc_signal< sc_lv<32> > p_Val2_14_fu_549_p3;
    sc_signal< sc_lv<32> > p_Val2_14_reg_759;
    sc_signal< sc_logic > ap_CS_fsm_state25;
    sc_signal< sc_lv<32> > y_0_reg_153;
    sc_signal< sc_lv<5> > i_0_reg_165;
    sc_signal< sc_lv<64> > zext_ln20_1_fu_201_p1;
    sc_signal< sc_lv<64> > zext_ln498_fu_262_p1;
    sc_signal< sc_logic > ap_CS_fsm_state17;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_lv<16> > mul_ln20_fu_210_p1;
    sc_signal< sc_lv<64> > p_Val2_s_fu_227_p1;
    sc_signal< sc_lv<6> > index_V_fu_252_p4;
    sc_signal< sc_lv<64> > zext_ln32_fu_281_p1;
    sc_signal< sc_lv<64> > p_Result_6_fu_285_p3;
    sc_signal< sc_lv<64> > p_Val2_5_fu_292_p2;
    sc_signal< sc_lv<52> > tmp_V_3_fu_316_p1;
    sc_signal< sc_lv<11> > tmp_V_2_fu_306_p4;
    sc_signal< sc_lv<1> > p_Result_7_fu_298_p3;
    sc_signal< sc_lv<52> > xs_sig_V_3_fu_320_p3;
    sc_signal< sc_lv<52> > xor_ln1309_fu_337_p2;
    sc_signal< sc_lv<1> > xs_sign_V_fu_332_p2;
    sc_signal< sc_lv<11> > xs_exp_V_fu_326_p3;
    sc_signal< sc_lv<52> > xs_sig_V_fu_343_p2;
    sc_signal< sc_lv<1> > or_ln849_fu_376_p2;
    sc_signal< sc_lv<64> > p_Result_5_fu_369_p3;
    sc_signal< sc_lv<64> > select_ln849_fu_380_p3;
    sc_signal< sc_lv<1> > xor_ln849_fu_391_p2;
    sc_signal< sc_lv<1> > and_ln849_fu_396_p2;
    sc_signal< sc_lv<64> > bitcast_ln849_fu_387_p1;
    sc_signal< sc_lv<1> > or_ln19_fu_408_p2;
    sc_signal< sc_lv<1> > and_ln19_fu_412_p2;
    sc_signal< sc_lv<64> > select_ln849_1_fu_401_p3;
    sc_signal< sc_lv<1> > and_ln19_1_fu_417_p2;
    sc_signal< sc_lv<64> > bitcast_ln475_fu_422_p1;
    sc_signal< sc_lv<64> > p_Val2_9_fu_426_p3;
    sc_signal< sc_lv<54> > mantissa_V_fu_456_p4;
    sc_signal< sc_lv<12> > zext_ln502_fu_469_p1;
    sc_signal< sc_lv<12> > add_ln502_fu_472_p2;
    sc_signal< sc_lv<11> > sub_ln1311_fu_486_p2;
    sc_signal< sc_lv<1> > isNeg_fu_478_p3;
    sc_signal< sc_lv<12> > sext_ln1311_fu_491_p1;
    sc_signal< sc_lv<12> > ush_fu_495_p3;
    sc_signal< sc_lv<32> > sext_ln1311_1_fu_503_p1;
    sc_signal< sc_lv<54> > zext_ln1285_fu_511_p1;
    sc_signal< sc_lv<137> > zext_ln682_fu_465_p1;
    sc_signal< sc_lv<137> > zext_ln1287_fu_507_p1;
    sc_signal< sc_lv<54> > r_V_fu_515_p2;
    sc_signal< sc_lv<1> > tmp_7_fu_527_p3;
    sc_signal< sc_lv<137> > r_V_1_fu_521_p2;
    sc_signal< sc_lv<32> > zext_ln662_fu_535_p1;
    sc_signal< sc_lv<32> > tmp_2_fu_539_p4;
    sc_signal< sc_logic > ap_CS_fsm_state26;
    sc_signal< sc_lv<32> > result_V_1_fu_557_p2;
    sc_signal< sc_lv<32> > p_Val2_15_fu_562_p3;
    sc_signal< sc_lv<20> > tmp_9_fu_576_p4;
    sc_signal< sc_lv<1> > tmp_8_fu_568_p3;
    sc_signal< sc_lv<1> > icmp_ln29_fu_586_p2;
    sc_signal< sc_lv<1> > or_ln27_fu_604_p2;
    sc_signal< sc_lv<16> > select_ln27_fu_596_p3;
    sc_signal< sc_lv<16> > empty_8_fu_592_p1;
    sc_signal< sc_lv<26> > ap_NS_fsm;
    sc_signal< sc_lv<32> > mul_ln20_fu_210_p10;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<26> ap_ST_fsm_state1;
    static const sc_lv<26> ap_ST_fsm_state2;
    static const sc_lv<26> ap_ST_fsm_state3;
    static const sc_lv<26> ap_ST_fsm_state4;
    static const sc_lv<26> ap_ST_fsm_state5;
    static const sc_lv<26> ap_ST_fsm_state6;
    static const sc_lv<26> ap_ST_fsm_state7;
    static const sc_lv<26> ap_ST_fsm_state8;
    static const sc_lv<26> ap_ST_fsm_state9;
    static const sc_lv<26> ap_ST_fsm_state10;
    static const sc_lv<26> ap_ST_fsm_state11;
    static const sc_lv<26> ap_ST_fsm_state12;
    static const sc_lv<26> ap_ST_fsm_state13;
    static const sc_lv<26> ap_ST_fsm_state14;
    static const sc_lv<26> ap_ST_fsm_state15;
    static const sc_lv<26> ap_ST_fsm_state16;
    static const sc_lv<26> ap_ST_fsm_state17;
    static const sc_lv<26> ap_ST_fsm_state18;
    static const sc_lv<26> ap_ST_fsm_state19;
    static const sc_lv<26> ap_ST_fsm_state20;
    static const sc_lv<26> ap_ST_fsm_state21;
    static const sc_lv<26> ap_ST_fsm_state22;
    static const sc_lv<26> ap_ST_fsm_state23;
    static const sc_lv<26> ap_ST_fsm_state24;
    static const sc_lv<26> ap_ST_fsm_state25;
    static const sc_lv<26> ap_ST_fsm_state26;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_14;
    static const sc_lv<32> ap_const_lv32_15;
    static const sc_lv<32> ap_const_lv32_16;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_18;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<64> ap_const_lv64_3F00000000000000;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<5> ap_const_lv5_17;
    static const sc_lv<5> ap_const_lv5_1;
    static const sc_lv<64> ap_const_lv64_409FFC0000000000;
    static const sc_lv<64> ap_const_lv64_0;
    static const sc_lv<32> ap_const_lv32_3F;
    static const sc_lv<32> ap_const_lv32_34;
    static const sc_lv<32> ap_const_lv32_3E;
    static const sc_lv<32> ap_const_lv32_39;
    static const sc_lv<11> ap_const_lv11_3FF;
    static const sc_lv<11> ap_const_lv11_433;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<52> ap_const_lv52_FFFFFFFFFFFFF;
    static const sc_lv<52> ap_const_lv52_0;
    static const sc_lv<11> ap_const_lv11_0;
    static const sc_lv<63> ap_const_lv63_0;
    static const sc_lv<64> ap_const_lv64_BFF0000000000000;
    static const sc_lv<12> ap_const_lv12_C01;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_35;
    static const sc_lv<32> ap_const_lv32_54;
    static const sc_lv<32> ap_const_lv32_19;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<20> ap_const_lv20_0;
    static const sc_lv<16> ap_const_lv16_0;
    static const sc_lv<16> ap_const_lv16_FFF;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_var_for_const1();
    void thread_ap_clk_no_reset_();
    void thread_add_ln502_fu_472_p2();
    void thread_and_ln19_1_fu_417_p2();
    void thread_and_ln19_fu_412_p2();
    void thread_and_ln849_fu_396_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state16();
    void thread_ap_CS_fsm_state17();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state21();
    void thread_ap_CS_fsm_state22();
    void thread_ap_CS_fsm_state23();
    void thread_ap_CS_fsm_state24();
    void thread_ap_CS_fsm_state25();
    void thread_ap_CS_fsm_state26();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_return();
    void thread_bitcast_ln475_fu_422_p1();
    void thread_bitcast_ln849_fu_387_p1();
    void thread_empty_8_fu_592_p1();
    void thread_i_fu_195_p2();
    void thread_icmp_ln18_fu_189_p2();
    void thread_icmp_ln19_1_fu_364_p2();
    void thread_icmp_ln19_fu_359_p2();
    void thread_icmp_ln29_fu_586_p2();
    void thread_icmp_ln849_1_fu_276_p2();
    void thread_icmp_ln849_fu_271_p2();
    void thread_index_V_fu_252_p4();
    void thread_isNeg_fu_478_p3();
    void thread_mantissa_V_fu_456_p4();
    void thread_mask_table1_address0();
    void thread_mask_table1_ce0();
    void thread_mul_ln20_fu_210_p1();
    void thread_mul_ln20_fu_210_p10();
    void thread_mul_ln20_fu_210_p2();
    void thread_or_ln19_fu_408_p2();
    void thread_or_ln27_fu_604_p2();
    void thread_or_ln849_fu_376_p2();
    void thread_p_Result_5_fu_369_p3();
    void thread_p_Result_6_fu_285_p3();
    void thread_p_Result_7_fu_298_p3();
    void thread_p_Result_8_fu_349_p4();
    void thread_p_Val2_14_fu_549_p3();
    void thread_p_Val2_15_fu_562_p3();
    void thread_p_Val2_5_fu_292_p2();
    void thread_p_Val2_9_fu_426_p3();
    void thread_p_Val2_s_fu_227_p1();
    void thread_r_V_1_fu_521_p2();
    void thread_r_V_fu_515_p2();
    void thread_result_V_1_fu_557_p2();
    void thread_select_ln24_fu_220_p3();
    void thread_select_ln27_fu_596_p3();
    void thread_select_ln849_1_fu_401_p3();
    void thread_select_ln849_fu_380_p3();
    void thread_sext_ln1311_1_fu_503_p1();
    void thread_sext_ln1311_fu_491_p1();
    void thread_sub_ln1311_fu_486_p2();
    void thread_tmp_2_fu_539_p4();
    void thread_tmp_7_fu_527_p3();
    void thread_tmp_8_fu_568_p3();
    void thread_tmp_9_fu_576_p4();
    void thread_tmp_V_1_fu_248_p1();
    void thread_tmp_V_2_fu_306_p4();
    void thread_tmp_V_3_fu_316_p1();
    void thread_tmp_V_5_fu_452_p1();
    void thread_trunc_ln368_fu_267_p1();
    void thread_ush_fu_495_p3();
    void thread_x_ant_address0();
    void thread_x_ant_ce0();
    void thread_x_coefs_address0();
    void thread_x_coefs_ce0();
    void thread_xor_ln1309_fu_337_p2();
    void thread_xor_ln849_fu_391_p2();
    void thread_xs_exp_V_fu_326_p3();
    void thread_xs_sig_V_3_fu_320_p3();
    void thread_xs_sig_V_fu_343_p2();
    void thread_xs_sign_V_fu_332_p2();
    void thread_y_1_fu_215_p2();
    void thread_zext_ln1285_fu_511_p1();
    void thread_zext_ln1287_fu_507_p1();
    void thread_zext_ln20_1_fu_201_p1();
    void thread_zext_ln32_fu_281_p1();
    void thread_zext_ln498_fu_262_p1();
    void thread_zext_ln502_fu_469_p1();
    void thread_zext_ln662_fu_535_p1();
    void thread_zext_ln682_fu_465_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
